topic:
  image: /camera/rgb/image_raw
  imu: /imu
  camera_info: /camera/rgb/camera_info

camera:
  fx: 1026.89
  fy: 1026.89
  cx: 960.5
  cy: 540.5

  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

extrinsic:
  Tbc: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]

aruco:
  n_markers: 22
  marker_size: 6
  marker_length: 0.4